weather_collector/channel/urls.py
from django.conf.urls import url

from . import views

app_name = 'channel'
urlpatterns = [
    url(r'^$', views.channel_list, name='list'),
    url(r'^register/$', views.register_channel, name='register'),
    url(r'^register/area/$', views.register_area, name='area'),
    url(r'^update/(?P<channel_id>\d+)/$', views.update_channel, name='update'),
    url(r'^delete/(?P<channel_id>\d+)/$', views.delete_channel, name='delete'),
]

weather_collector/weather/urls.py
from django.conf.urls import url

from . import views

app_name = 'weather'
urlpatterns = [
    url(r'^$', views.select_area, name='select_area'),
    url(r'^weekly/(?P<area_id>\d+)/$', views.weekly_weather, name='weekly'),
    url(r'^daily/(?P<weather_id>\d+)/$', views.daily_weather, name='daily'),
]

weather_collector/weather_collector/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^weather/', include('weather.urls')),
    url(r'^channel/', include('channel.urls')),
]

weather_collector/weather/models.py
from django.db import models
from django.utils.timezone import now


class Area(models.Model):
    """
    天気予報の対象地域
    """
    name = models.CharField("地域", max_length=200)

    def __str__(self):
        return self.name


class Channel(models.Model):
    """
    天気予報サイトのURL

    各天気予報サイトのURLは、ひとつのAreaに紐づく。
    """

    TYPE_WEEKLY = 0
    TYPE_DAILY = 1

    TYPE_CHOICES = (
        (TYPE_WEEKLY, '週間天気'),
        (TYPE_DAILY, '今日の天気'),
    )

    CHANNEL_YAHOO = 0
    CHANNEL_TENKIJP = 1
    # CHANNEL_WEATHERNEWS = 2

    CHANNEL_CHOICES = (
        (CHANNEL_YAHOO, 'Yahoo!天気'),
        (CHANNEL_TENKIJP, '日本気象協会 tenki.jp'),
        # (CHANNEL_WEATHERNEWS, 'ウェザーニュース'),
    )

    area = models.ForeignKey(Area, on_delete=models.CASCADE, )

    name = models.PositiveIntegerField(
                "チャンネル",
                choices=CHANNEL_CHOICES,
            )
    weather_type = models.PositiveIntegerField(
                "予報タイプ",
                choices=TYPE_CHOICES,
            )
    url = models.URLField(max_length=1000)

    def __str__(self):
        return self.area.name + '-' + \
                self.get_name_display() + '-' + \
                self.get_weather_type_display()


class Weather(models.Model):
    """
    1日分の天気予報

    各1日分の天気予報はひとつのChannelに紐付く。
    """
    WEEKDAY_JA = [
        '月', '火', '水', '木', '金', '土', '日',
    ]

    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)

    date = models.DateField('日付', default=now)
    weather = models.CharField('天気', max_length=200)
    highest_temperatures = models.IntegerField('最高気温（℃）', default=20)
    lowest_temperatures = models.IntegerField('最低気温（℃）', default=20)
    chance_of_rain = models.PositiveIntegerField('降水確率（％）', default=0)
    wind_speed = models.PositiveIntegerField(
            '風速（m/s）',
            default=0,
            blank=True,
            null=True
        )

    acquisition_date = models.DateTimeField('取得日時', auto_now=True)

    def __str__(self):
        return str(self.channel) + '-' + self.date.strftime('%Y/%m/%d')

    # Display Properties

    def date_display(self):
        return self.date.strftime('%m/%d')

    def weekday_display(self):
        return self.WEEKDAY_JA[self.date.weekday()]

    def chance_of_rain_display(self):
        if self.chance_of_rain == 999:
            return '---'
        else:
            return self.chance_of_rain


class HourlyWeather(models.Model):
    """
    n時間分の天気予報

    n時間分の天気予報はひとつのWeatherに紐付く。
    """
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    date = models.ForeignKey(Weather, on_delete=models.CASCADE)

    time = models.TimeField('時', default=now)
    weather = models.CharField('天気', max_length=200)
    temperatures = models.DecimalField('気温（℃）', max_digits=4, decimal_places=1, default=20)
    humidity = models.PositiveIntegerField('湿度（％）', default=50)
    precipitation = models.PositiveIntegerField(
                '降水量（mm/h）',
                blank=True,
                null=True
            )
    chance_of_rain = models.PositiveIntegerField(
                '降水確率（％）',
                blank=True,
                null=True
            )
    wind_direction = models.CharField('風向', max_length=200)
    wind_speed = models.PositiveIntegerField(
                '風速（m/s）',
                blank=True,
                null=True
            )

    acquisition_date = models.DateTimeField('取得日時', auto_now=True)

    def __str__(self):
        return self.date.date.strftime('%Y/%m/%d') + \
                self.time.strftime('%H/%M/%S')

    def chance_of_rain_display(self):
        worthless_values = [999, None]
        if self.chance_of_rain in worthless_values:
            return('---')
        else:
            return self.chance_of_rain

weather_collector/weather/forms.py
from django import forms

from .models import Area


class AreaChoiceForm(forms.Form):

    queryset = Area.objects.order_by(
                            '-id'
                        )
    selected_area = forms.ModelChoiceField(label='地域', queryset=queryset)

weather_collector/weather/views.py
from django.template.response import TemplateResponse
from django.shortcuts import redirect  # , get_object_or_404
from django.contrib import messages

import logging
from datetime import date

from .models import Area, Channel, Weather, HourlyWeather
from .forms import AreaChoiceForm
from .import scrapyutils


logger = logging.getLogger(__name__)


def get_today():
    return date.today()


def weekly_weather(request, area_id):
    """
    選択したエリアの、週間天気予報を表示する。
    """
    logger.info('***** Started %s. *****', 'weekly_weather')

    # 時刻は00:00:00で取得
    today = get_today()

    area = Area.objects.get(id=area_id)
    channels = Channel.objects.filter(
                            area_id=area_id,
                            weather_type=Channel.TYPE_WEEKLY
                        ).order_by(
                            'id'
                        )

    all_weekly_weather = {}
    if not channels:
        # チャンネルが存在しない場合は、週間天気予報画面にチャンネル登録を促すメッセージを表示。
        messages.warning(request, 'チャンネルが登録されていません。')
        logger.info('Channel was not registered.')
    else:
        for channel in channels:
            weekly_weather_per_channel = Weather.objects.filter(
                                channel=channel.id,
                                date__gte=today
                            ).order_by(
                                'channel_id',
                                'date'
                            ).extra(
                                select={
                                    'daily_weather_count':
                                    'SELECT COUNT(*) FROM weather_hourlyweather WHERE weather_weather.id = weather_hourlyweather.date_id'
                                },
                            )
            all_weekly_weather[channel.get_name_display()] = weekly_weather_per_channel

    logger.info('Response template "%s".', 'weather/weekly.html')
    logger.info('***** Ended %s. *****', 'weekly_weather')

    return TemplateResponse(
                                request,
                                'weather/weekly.html',
                                {
                                    'area': area,
                                    'all_weekly_weather': all_weekly_weather
                                }
                            )


def daily_weather(request, weather_id):
    """
    選択した日付の、時間ごと天気予報を表示する。
    """
    logger.info('***** Started %s. *****', 'daily_weather')

    daily_weather = HourlyWeather.objects.filter(
                            date=weather_id
                        ).order_by(
                            'time'
                        )
    weather = Weather.objects.select_related(
                            'channel'
                        ).get(
                            id=weather_id
                        )

    logger.info('Response template "%s".', 'weather/daily.html')
    logger.info('***** Ended %s. *****', 'daily_weather')
    return TemplateResponse(
                                request,
                                'weather/daily.html',
                                {
                                    'daily_weather': daily_weather,
                                    'weather': weather
                                }
                            )


def select_area(request):
    """
    『お天気エリア選択』画面

    * POSTでアクセスされた場合
     『お天気エリア選択』画面で選択した"Area"に紐づくすべての"Channel"の天気予報を取得し、DBへ登録する。
    * GETでアクセスされた場合
     『お天気エリア選択』画面を表示する。
    """
    logger.info('***** Started %s. *****', 'select_area')
    if request.method == 'POST':
        # 選択された地域を取得
        form = AreaChoiceForm(data=request.POST)
        if form.is_valid():
            area_id = form.cleaned_data['selected_area'].id
            logger.info('area_id: %d was selected.', area_id)

            if 'scrapy_weather' in request.POST:
                # 「天気予報を取得」ボタンを押下時処理。
                logger.info('"scrapy_weather" was requested.')

                channels = Channel.objects.filter(
                                area=area_id
                            ).order_by(
                                'id'
                            )
                if not channels:
                    # チャンネルが存在しない場合は、スクレイピングは行わない。
                    logger.info('Channel was not registered.')
                else:
                    # 天気予報取得対象URL、CSV出力
                    scrapyutils.output_target_urls_to_csv(channels)

                    # weatherscrapy実行
                    file_names = scrapyutils.execute_scrapy(channels)

                    # CSV出力された天気予報をDBへ登録する。
                    scrapyutils.register_scrapped_weather(area_id, file_names)

            # 「天気予報を取得」ボタン、「週間天気予報を表示」ボタンともに週間天気予表示viewにリダイレクト
            logger.info('Redirect "%s".', 'weather:weekly')
            logger.info('***** Ended %s. *****', 'select_area')

            return redirect('weather:weekly', area_id=area_id)
        else:
            # バリデーションエラー時は、『お天気エリア選択画面』に戻る
            logger.info('ValidationError "%s".', 'AreaChoiceForm')
    else:
        # 『お天気エリア選択画面』初期表示処理
        form = AreaChoiceForm()

    logger.info('Response template "%s".', 'weather/select_area.html')
    logger.info('***** Ended %s. *****', 'select_area')

    return TemplateResponse(request, 'weather/select_area.html', {'form': form})

weather_collector/weather/templates/weather/area.html
{% extends 'base.html' %}
{% block title %}地域を選択{% endblock %}
{% block content %}
<h1>地域を選択</h1>
  <form method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <p>
        <input type="submit" value="天気予報を取得" name="scrapy_weather" />
    </p>
    <p>
        <input type="submit" value="週間天気予報を表示" name="display_weekly" />
    </p>
  </form>
{% endblock %}

weather_collector/weather/templates/weather/daily.html
{% extends 'base.html' %}
{% block title %}天気予報{% endblock %}
{% block content %}
  <h1>{{ weather.channel.area.name }}&nbsp;{{ weather.date_display }}({{ weather.weekday_display }})の天気予報</h1>
  <h2>{{ weather.channel.get_name_display }}</h2>
  <table>
    <thead>
      <tr>
        <th>時間</th>
        <th>天気</th>
        <th>気温（℃）</th>
        <th>降水量（mm/h）</th>
        <th>風向</th>
        <th>風速（m/s）</th>
      </tr>
    </thead>
    <tbody>
      {% for hourly_weather in daily_weather %}
        <tr>
          <td>{{ hourly_weather.time }}</td>
          <td>{{ hourly_weather.weather }}</td>
          <td align=center>{{ hourly_weather.temperatures }}</td>
          <td align=center>{{ hourly_weather.precipitation }}</td>
          <td align=center>{{ hourly_weather.wind_direction }}</td>
          <td align=center>{{ hourly_weather.wind_speed }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="6">天気予報ないよ</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <p>
    <a href="{% url 'weather:weekly' area_id=weather.channel.area.id %}" class="button">
      {{ weather.channel.area.name }}の週間天気に戻る
    </a>
  </p>
  <br>
{% endblock %}

weather_collector/weather/templates/weather/select_area.html
{% extends 'base.html' %}
{% block title %}地域を選択{% endblock %}
{% block content %}
<h1>地域を選択</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <p>
      <input type="submit" value="天気予報を取得" name="scrapy_weather" />
  </p>
  <p>
      <input type="submit" value="週間天気予報を表示" name="display_weekly" />
  </p>
</form>
{% endblock %}

weather_collector/weather/templates/weather/weekly.html
{% extends 'base.html' %}
{% block title %}週間天気{% endblock %}
{% block content %}
  <h1>{{ area.name }}の週間天気予報</h1>

  {% if messages %}
    {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
        <p class="messages">
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
          &nbsp;&nbsp;&nbsp;
          <a href="{% url 'channel:register' %}" class="button">チャンネルを新規登録</a>
        <p>
      {% endif %}
    {% endfor %}
  {% endif %}

  {% for channel_name, weekly_weather_per_channel in all_weekly_weather.items %}
    <h2>{{ channel_name }}</h2>
    <table>
      <thead>
        <tr>
          <th>日付&nbsp;&nbsp;</th>
          <th>天気&nbsp;&nbsp;</th>
          <th>最高気温（℃）</th>
          <th>最低気温（℃）</th>
          <th>降水確率（％）</th>
          <th>数えた</th>
        </tr>
      </thead>
      <tbody>
        {% for weather in weekly_weather_per_channel %}
          <tr>
            <td>
              {% if weather.daily_weather_count == 0 %}
                {{ weather.date_display }}&nbsp;({{ weather.weekday_display }})
              {% else %}
                <a href="{% url 'weather:daily' weather_id=weather.id %}">
                  {{ weather.date_display }}&nbsp;({{ weather.weekday_display }})
                </a>
              {% endif %}
            </td>
            <td>{{ weather.weather }}</td>
            <td align=center>{{ weather.highest_temperatures }}</td>
            <td align=center>{{ weather.lowest_temperatures }}</td>
            <td align=center>{{ weather.chance_of_rain_display }}</td>
            <td align=center>{{ weather.daily_weather_count }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="6">天気予報ないよ</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <br>
  {% endfor %}
{% endblock %}