weather_collector/channel/urls.py
from django.conf.urls import url

from . import views

app_name = 'channel'
urlpatterns = [
    url(r'^$', views.channel_list, name='list'),
    url(r'^register/$', views.register_channel, name='register'),
    url(r'^register/area/$', views.register_area, name='area'),
    url(r'^update/(?P<channel_id>\d+)/$', views.update_channel, name='update'),
    url(r'^delete/(?P<channel_id>\d+)/$', views.delete_channel, name='delete'),
]

weather_collector/weather/urls.py
from django.conf.urls import url

from . import views

app_name = 'weather'
urlpatterns = [
    url(r'^$', views.select_area, name='select_area'),
    url(r'^weekly/(?P<area_id>\d+)/$', views.weekly_weather, name='weekly'),
    url(r'^daily/(?P<weather_id>\d+)/$', views.daily_weather, name='daily'),
]

weather_collector/weather_collector/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^weather/', include('weather.urls')),
    url(r'^channel/', include('channel.urls')),
]

weather_collector/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="UTF-8">
    <title>わたしのお天気 - {% block title %}{% endblock %}</title>
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css" />
    <link href="//fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet" />
  </head>

  <body>
    {% block header %}
      <div class="header">
        <div class="wrapper">
          <ul>
              <li><a class="brand" href="{% url 'weather:select_area' %}">my weather</a></li>
          </ul>
          <ul>
              <li><a class="brand" href="{% url 'channel:list' %}">channel</a></li>
          </ul>
        </div>
      </div>
    {% endblock %}

    <div class="wrapper">
      {% block content %}
      {% endblock %}
    </div>
  </body>

</html>