weather_collector/channel/urls.py
from django.conf.urls import url

from . import views

app_name = 'channel'
urlpatterns = [
    url(r'^$', views.channel_list, name='list'),
    url(r'^register/$', views.register_channel, name='register'),
    url(r'^register/area/$', views.register_area, name='area'),
    url(r'^update/(?P<channel_id>\d+)/$', views.update_channel, name='update'),
    url(r'^delete/(?P<channel_id>\d+)/$', views.delete_channel, name='delete'),
]

weather_collector/weather_collector/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^weather/', include('weather.urls')),
    url(r'^channel/', include('channel.urls')),
]

weather_collector/channel/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from weather.models import Area, Channel


class ChannelRegistrationForm(forms.Form):
    """
    チャンネル登録用のフォーム
    """
    area_queryset = Area.objects.order_by('id')
    list_channel_choices = list(Channel.CHANNEL_CHOICES)
    list_channel_choices.insert(0, ('', '---------'))

    area = forms.ModelChoiceField(label='地域', queryset=area_queryset)
    channel = forms.ChoiceField(label='チャンネル', choices=list_channel_choices)

    weather_type_weekly_url = forms.URLField(max_length=255, label='週間天気予報のURL')
    weather_type_daily_url = forms.URLField(max_length=255, label='今日の天気予報のURL')


class ChannelEditForm(forms.ModelForm):
    """
    チャンネル変更用のフォーム
    """
    class Meta:
        model = Channel
        fields = [
            'url',
        ]
        labels = {
            'url': _('URL'),
        }


class AreaRegistrationForm(forms.ModelForm):
    """
    地域登録用のフォーム
    """
    class Meta:
        model = Area
        fields = [
            'name',
        ]

weather_collector/channel/views.py
from django.template.response import TemplateResponse
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages

import logging

from weather.models import Channel
from .forms import ChannelRegistrationForm, ChannelEditForm, AreaRegistrationForm


logger = logging.getLogger(__name__)


def channel_list(request):
    """
    登録済みのチャンネルリストを表示する。
    """
    logger.info('***** Started %s. *****', 'channel_list')

    channels = Channel.objects.select_related(
                        'area'
                    ).order_by(
                        'area_id',
                        'name',
                        'weather_type',
                    )

    logger.info('Response template "%s".', 'channel/list.html')
    logger.info('***** Ended %s. *****', 'channel_list')
    return TemplateResponse(
                                request,
                                'channel/list.html',
                                {
                                   'channels': channels,
                                }
                            )


def _is_duplicate_channels(form_cleaned_data):
    """
    重複するチャンネルは登録できないチェック
    """
    area = form_cleaned_data['area']
    channel = form_cleaned_data['channel']

    channels = Channel.objects.select_related(
          'area'
      ).filter(
          area=area,
          name=channel,
      )
    if channels:
        return True
    return False


def register_channel(request):
    """
    チャンネルを新規登録する
    """
    logger.info('***** Started %s. *****', 'register_channel')
    if request.method == 'POST':

        form = ChannelRegistrationForm(data=request.POST)

        if form.is_valid():

            if _is_duplicate_channels(form.cleaned_data):
                messages.error(
                    request,
                    'チャンネル「{} * {}」はすでに登録されています。'.format(
                        form.cleaned_data['area'],
                        Channel.CHANNEL_CHOICES[int(form.cleaned_data['channel'])][1]
                    )
                )
                logger.info(
                    'Duplicate channels "Area:%s - Channel:%s".',
                    form.cleaned_data['area'].id,
                    form.cleaned_data['channel']
                )
                logger.info('Response template "%s".', 'channel/register.html')
                logger.info('***** Ended %s. *****', 'register_channel')
                return TemplateResponse(
                                            request,
                                            'channel/register.html',
                                            {
                                                'form': form,
                                            }
                                        )

            # 確認画面からのPOSTの場合、チャンネルを登録する。
            if 'confirmed' in request.POST and request.POST['confirmed'] == '1':
                # 「登録する」ボタン押下時
                if 'register' in request.POST:
                    # 週間天気の登録
                    Channel.objects.create(
                        area=form.cleaned_data['area'],
                        name=form.cleaned_data['channel'],
                        weather_type=Channel.TYPE_WEEKLY,
                        url=form.cleaned_data['weather_type_weekly_url'],
                    )

                    # 今日の天気の登録
                    Channel.objects.create(
                        area=form.cleaned_data['area'],
                        name=form.cleaned_data['channel'],
                        weather_type=Channel.TYPE_DAILY,
                        url=form.cleaned_data['weather_type_daily_url'],
                    )

                    messages.info(
                        request,
                        'チャンネル「{} * {}」を登録しました。'.format(
                            form.cleaned_data['area'],
                            Channel.CHANNEL_CHOICES[int(form.cleaned_data['channel'])][1]
                        )
                    )
                    logger.info('Registered to Channel.')
                    logger.info('Redirect "%s".', 'channel:list')
                    logger.info('***** Ended %s. *****', 'register_channel')
                    return redirect('channel:list')
                else:
                    # 「戻る」ボタン押下時。入力画面へ戻る。
                    logger.info('"back" was requested.')
            else:
                # 入力画面からのPOSTの場合、確認画面を表示する。
                # 表示用のチャンネル名。何か変な気がする。自信ないけどとりあえずこれで動く。
                channel_display = Channel.CHANNEL_CHOICES[int(form.cleaned_data['channel'])][1]

                logger.info('Response template "%s".', 'channel/register_confirm.html')
                logger.info('***** Ended %s. *****', 'register_channel')
                return TemplateResponse(
                                            request,
                                            'channel/register_confirm.html',
                                            {
                                                'form': form,
                                                'modified': form.cleaned_data,
                                                'channel_display': channel_display,
                                            }
                                        )

        else:
            logger.info('ValidationError "%s".', 'ChannelRegistrationForm')
    else:
        # チャンネル登録画面を表示する
        form = ChannelRegistrationForm()

    logger.info('Response template "%s".', 'channel/register.html')
    logger.info('***** Ended %s. *****', 'register_channel')
    return TemplateResponse(
                                request,
                                'channel/register.html',
                                {
                                    'form': form,
                                }
                            )


def update_channel(request, channel_id):
    """
    チャンネルを変更する
    """
    logger.info('***** Started %s. *****', 'update_channel')

    channel = get_object_or_404(Channel, id=channel_id)

    if request.method == 'POST':
        # チャンネルを変更する
        form = ChannelEditForm(data=request.POST, instance=channel)
        if form.is_valid():
            form.save()

            messages.info(
                request,
                'チャンネル「{} * {} * {}」を変更しました。'.format(
                    channel.area.name,
                    channel.get_name_display(),
                    channel.get_weather_type_display(),
                )
            )
            logger.info('Updated to Channel.')
            logger.info('Redirect "%s".', 'channel:list')
            logger.info('***** Ended %s. *****', 'update_channel')
            return redirect('channel:list')
        else:
            logger.info('ValidationError "%s".', 'ChannelEditForm')

    else:
        # 『チャンネル変更』画面を初期表示する
        form = ChannelEditForm(instance=channel)

    logger.info('Response template "%s".', 'channel/edit.html')
    logger.info('***** Ended %s. *****', 'update_channel')
    return TemplateResponse(
                                request,
                                'channel/edit.html',
                                {
                                    'form': form,
                                    'channel': channel,
                                }
                            )


def delete_channel(request, channel_id):
    """
    チャンネルを削除する
    """
    logger.info('***** Started %s. *****', 'delete_channel')
    channel = get_object_or_404(Channel, id=channel_id)

    # チャンネルを削除する
    # 週間天気用と今日の天気用の両方同時に削除する。
    Channel.objects.filter(
                            area=channel.area,
                            name=channel.name,
                        ).delete()

    messages.info(request, 'チャンネル「{} * {}」を削除しました。'.format(channel.area.name, channel.get_name_display()))
    logger.info('Deleted to Channel: "%s - %s"', channel.area, channel.get_name_display())
    logger.info('Redirect "%s".', 'channel:list')
    logger.info('***** Ended %s. *****', 'delete_channel')
    return redirect('channel:list')


def register_area(request):
    """
    地域を登録する
    """
    logger.info('***** Started %s. *****', 'register_area')

    if request.method == 'POST':
        # 地域を登録する
        form = AreaRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            messages.info(request, '地域「{}」を登録しました。'.format(form.cleaned_data['name']))
            logger.info('Registed to Area.')
            logger.info('Redirect "%s".', 'channel:register')
            logger.info('***** Ended %s. *****', 'register_area')
            return redirect('channel:register')
        else:
            logger.info('ValidationError "%s".', 'AreaRegistrationForm')
    else:
        # 『地域を登録する』画面を初期表示する
        form = AreaRegistrationForm()

    logger.info('Response template "%s".', 'channel/register_area.html')
    logger.info('***** Ended %s. *****', 'register_area')
    return TemplateResponse(
                                request,
                                'channel/register_area.html',
                                {
                                    'form': form,
                                }
                            )

weather_collector/channel/templates/channel/edit.html
{% extends 'base.html' %}
{% block title %}チャンネル変更{% endblock %}
{% block content %}
<h1>チャンネルを変更する</h1>
<form method="post" action="{% url 'channel:update' channel_id=channel.id %}">
  {% csrf_token %}

  <table class="edit-ch">
    <tbody>
      <tr>
        <th>地域:</th>
        <td>{{ channel.area }}</td>
      </tr>
      <tr>
        <th>チャンネル:</th>
        <td>{{ channel.get_name_display }}</td>
      </tr>
      <tr>
        <th>予報タイプ:</th>
        <td>{{ channel.get_weather_type_display }}</td>
      </tr>
      {{ form.as_table }}
    </tbody>
  </table>
  <br>
  <p>
    <input type="submit" value="変更する" />
  </p>
</form>
{% endblock %}

weather_collector/channel/templates/channel/list.html
{% extends 'base.html' %}
{% block title %}チャンネル{% endblock %}
{% block content %}
<h1>チャンネルリスト</h1>

{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
        <p class="messages">
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
        <p>
        {% endif %}
    {% endfor %}
{% endif %}

<table>
    <thead>
        <tr>
            <th>地域</th>
            <th>チャンネル</th>
            <th>予報タイプ</th>
            <th>URL</th>
            <th>変更</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        {# 一覧用 #}
        {% for channel in channels %}
        <tr>
            <td>{{ channel.area.name }}</td>
            <td>{{ channel.get_name_display }}</td>
            <td>{{ channel.get_weather_type_display }}</td>
            <td width=120px>
                <span class="small">{{ channel.url }}</span>
            </td>
            <td><a href="{% url 'channel:update' channel_id=channel.id %}">変更</a></td>
            {% if channel.weather_type == channel.TYPE_WEEKLY %}
                <td rowspan="2">
                    <a href="{% url 'channel:delete' channel_id=channel.id %}">削除</a>
                </td>
            {% endif %}
        </tr>
        {% empty %} {# チャンネルがない場合 #}
        <tr>
            <td colspan="6">チャンネルないよ</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br>
<p>
    <a href="{% url 'channel:register' %}" class="button">チャンネルを新規登録</a>
</p>
{% endblock %}

weather_collector/channel/templates/channel/register.html
{% extends 'base.html' %}
{% block title %}チャンネル登録{% endblock %}
{% block content %}

<h1>チャンネルを新規登録</h1>

{% if messages %}
  {% for message in messages %}
      <p class="messages">
        <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
      <p>
  {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}

  <table class="edit-ch">
      {{ form.as_table }}
  </table>
  <br>
  <p>
      <input type="submit" value="確認する" />
      <a href="{% url 'channel:area' %}" class="button-orange right">地域を登録する</a>
  </p>
</form>
{% endblock %}

weather_collector/channel/templates/channel/register_area.html
{% extends 'base.html' %}
{% block title %}地域登録{% endblock %}
{% block content %}
<h1>地域を登録する</h1>
  <form method="post">
    {% csrf_token %}

    <table class="edit-ch">
      {{ form.as_table }}
    </table>
    <br>
    <p>
      <input type="submit" value="登録する" />
    </p>
  </form>
{% endblock %}

weather_collector/channel/templates/channel/register_confirm.html
{% extends 'base.html' %}
{% block title %}チャンネル登録確認{% endblock %}
{% block content %}
<h1>チャンネルを新規登録確認</h1>

{% if messages %}
  {% for message in messages %}
      <p class="messages">
        <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
      <p>
  {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}

  <input type="hidden" name="confirmed" value="1" />
  {% for field in form %}
    {{ field.as_hidden }}
  {% endfor %}

  <table class="edit-ch">
    <tbody>
      <tr>
        <th>地域:</th>
        <td>{{ modified.area }}</td>
      </tr>
      <tr>
        <th>チャンネル:</th>
        <td>{{ channel_display }}</td>
      </tr>
      <tr>
        <th>週間天気予報のURL:</th>
        <td>
          <span class="small">{{ modified.weather_type_weekly_url }}</span>
        </td>
      </tr>
      <tr>
        <th>今日の天気予報のURL:</th>
        <td><span class="small">{{ modified.weather_type_daily_url }}</span></td>
      </tr>
    </tbody>
  </table>
  <br>
  <p>
    <span><input type="submit" value="登録する"  name="register" /></span>&nbsp;&nbsp;&nbsp;
    <span class="right"><input type="submit" value="戻る"  name="back" /></span>
  </p>
</form>
{% endblock %}